var_make_debian: move code to generate the kernel configuration up
This avoid the following errors:

ERROR: Kernel configuration is invalid.
       include/generated/autoconf.h or include/config/auto.conf are missing.
       Run 'make oldconfig && make prepare' on kernel src to fix it.

Signed-off-by: FrancescoFerraro <francesco.f@variscite.com>